version: '3.8'

services:
  web:
    build: .
    container_name: app_matriculas
    restart: always
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=clave_secreta_produccion_cambiar_esto
      - ALLOWED_HOSTS=*
      - DB_NAME=db_matriculas
      - DB_USER=root
      - DB_PASSWORD=tu_password_seguro_root
      - DB_HOST=db_central
      - DB_PORT=3306
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_matriculas
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
    external: true