version: '3.8'

services:
  web:
    build: .
    container_name: app_matriculas
    restart: always
    ports:
      - "8002:8000"  # Puerto externo 8002
    environment:
      - DEBUG=1
      - SECRET_KEY=clave_secreta_produccion_cambiar_esto
      - ALLOWED_HOSTS=*
      # Datos de conexión a la BD Central
      - DB_NAME=db_matriculas
      - DB_USER=root
      - DB_PASSWORD=tu_password_seguro_root  # <--- ¡PON LA MISMA CLAVE QUE EN INFRA!
      - DB_HOST=db_central
      - DB_PORT=3306
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
    external: true
