# Generated by Django 5.2.15 on 2026-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivopublicacion',
            options={'ordering': ['orden'], 'verbose_name': 'Archivo de Publicación', 'verbose_name_plural': 'Archivos de Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='fotoevento',
            options={'ordering': ['orden'], 'verbose_name': 'Foto de Evento', 'verbose_name_plural': 'Fotos de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='recursomarketing',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Recurso de Marketing', 'verbose_name_plural': 'Recursos de Marketing'},
        ),
        migrations.AlterUniqueTogether(
            name='copypublicacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/publicaciones/portadas/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='copypublicacion',
            constraint=models.UniqueConstraint(fields=('publicacion', 'plataforma'), name='unique_publicacion_plataforma'),
        ),
    ]
