# Generated by Django 5.2.15 on 2026-06-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_archivopublicacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copypublicacion',
            options={'verbose_name': 'Copy', 'verbose_name_plural': 'Copies'},
        ),
        migrations.RemoveField(
            model_name='copypublicacion',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='copypublicacion',
            name='hashtags',
        ),
    ]
