# Generated by Django 5.2.15 on 2026-06-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_copypublicacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='responsable',
        ),
    ]
