# Generated by Django 5.2.15 on 2026-06-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_remove_evento_fecha_fin_remove_evento_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='creado_por',
        ),
    ]
