# Generated by Django 5.2.15 on 2026-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_remove_publicacion_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='portada',
        ),
        migrations.AddField(
            model_name='archivopublicacion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/publicaciones/thumbnails/'),
        ),
    ]
