# Generated by Django 5.2.15 on 2026-08-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_remove_publicacion_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copypublicacion',
            name='texto_principal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='copypublicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
