# Generated by Django 5.2.17 on 2026-08-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_copypublicacion_texto_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoevento',
            options={'ordering': ['orden'], 'verbose_name': 'Media de Evento', 'verbose_name_plural': 'Media de Eventos'},
        ),
        migrations.AddField(
            model_name='fotoevento',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/eventos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='fotoevento',
            name='imagen',
            field=models.FileField(upload_to='marketing/eventos/media/'),
        ),
    ]
