# Generated by Django 5.2.17 on 2026-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_fotoevento_options_fotoevento_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursomarketing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/recursos/thumbnails/'),
        ),
    ]
