# Generated by Django 5.2.17 on 2026-08-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_recursomarketing_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='alcance',
            field=models.TextField(blank=True, help_text='Describe el alcance de la publicación, incluyendo objetivos y público objetivo.'),
        ),
    ]
