# Generated by Django 5.2.17 on 2026-08-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_publicacion_alcance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Alcance',
                'verbose_name_plural': 'Alcances',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='alcance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='marketing.alcance'),
        ),
    ]
