# Generated by Django 5.2.17 on 2026-08-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alcance_alter_publicacion_alcance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='alcance',
        ),
    ]
