# Generated by Django 5.2.17 on 2026-08-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_remove_publicacion_alcance'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='alcance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='marketing.alcance'),
        ),
    ]
