from .alumnosviews import *
from .admin import *
from .apoderadosviews import *
from .matriculasviews import *
from .cuotas import *
from .ajaxviews import *
from .usuarios import *
from .ciclos_turnos_horarios import *
from .ventas import *