# Generated by Django 5.2.7 on 2025-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0006_alter_matricula_tipo_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='abreviatura',
            field=models.CharField(choices=[('Señor', 'Señor'), ('Señora', 'Señora')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_alumno',
            field=models.CharField(choices=[('pre_uni_promo', 'Pre Universitario Promoción'), ('pre_uni_excelencia', 'Pre Universitario Excelencia'), ('pre_uni_provincia', 'Pre Universitario Provincia'), ('pre_uni_virtual', 'Pre Universitario Virtual'), ('3_4_5_preferente', '3ro, 4to y 5to Preferente'), ('1_2_3_basico', '1ro, 2do y 3ro Básico'), ('cepunc_manana', 'CEPUNC Mañana'), ('cepunc_tarde', 'CEPUNC Tarde')], default='pre_uni_promo', max_length=20),
        ),
    ]
