# Generated by Django 5.1.3 on 2025-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0007_apoderado_abreviatura_alter_matricula_tipo_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fondo_social',
            field=models.BooleanField(default=False),
        ),
    ]
