# Generated by Django 5.2.9 on 2026-02-11 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_alter_matricula_uuid_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('costo', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Costo S/.')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.ciclo')),
            ],
            options={
                'verbose_name': 'Simulacro',
                'verbose_name_plural': 'Simulacros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(choices=[('no_dio', 'No dió'), ('si', 'Pag'), ('fondo', 'Fondo'), ('debe', 'Debe')], default='no_dio', max_length=10)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='matriculas.simulacro')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'unique_together': {('simulacro', 'matricula')},
            },
        ),
    ]
