# Generated by Django 5.2.9 on 2026-02-11 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_simulacro_asistenciasimulacro'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculas.turno', verbose_name='Turno destinado'),
        ),
    ]
