# Generated by Django 5.2.11 on 2026-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0012_simulacro_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto_lado',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/fotos_lado/'),
        ),
    ]
