# Generated by Django 5.2.12 on 2026-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0015_venta_ventaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
