# Generated by Django 5.2.12 on 2026-04-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0016_apoderado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='tipo_matricula',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('promocion', 'PROMOCION'), ('beca50', 'BECA 50%'), ('beca100', 'BECA 100%'), ('fondo_social', 'FONDO SOCIAL'), ('exalumno', 'EXALUMNO'), ('gerencia', 'GERENCIA')], default='regular', max_length=20),
        ),
    ]
