# Generated by Django 5.2.12 on 2026-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0018_procedimiento_paso_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
