# Generated by Django 5.2.12 on 2026-04-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0019_procedimiento_observacion_delete_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Formato de registro, Tutorial de sistema', max_length=150)),
                ('tipo', models.CharField(choices=[('DOC', 'Documento (PDF, Word, Excel)'), ('IMG', 'Imagen o Captura'), ('VID', 'Enlace de Video (YouTube/Drive)')], default='DOC', max_length=3)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='procesos/recursos/')),
                ('enlace_video', models.URLField(blank=True, max_length=500, null=True)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='matriculas.paso')),
            ],
        ),
    ]
