# Generated by Django 5.2.12 on 2026-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0020_recursopaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='procesos/recursos/'),
        ),
        migrations.AddField(
            model_name='paso',
            name='enlace_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='RecursoPaso',
        ),
    ]
