# Generated by Django 5.2.12 on 2026-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0021_paso_archivo_paso_enlace_video_delete_recursopaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='boletas',
            field=models.FileField(blank=True, null=True, upload_to='boletas/'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='constancia_matricula',
            field=models.FileField(blank=True, null=True, upload_to='constancias/'),
        ),
    ]
