# Generated by Django 5.2.12 on 2026-04-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0022_matricula_boletas_matricula_constancia_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='boletas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='constancia_matricula',
        ),
    ]
