# Generated by Django 5.2.12 on 2026-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0023_remove_matricula_boletas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='foto_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/'),
        ),
    ]
