# Generated by Django 5.2.17 on 2026-08-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0026_alter_matricula_usuario_registro_alter_pago_usuario_registro_alter_perfil_user_alter_procedimiento_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
