# Generated by Django 5.2.17 on 2026-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0027_pago_fecha_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='boleta_sunat',
            field=models.FileField(blank=True, null=True, upload_to='pagos/boletas_sunat/'),
        ),
    ]
