# Generated by Django 5.2.17 on 2026-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0028_pago_boleta_sunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cod_boleta_sunat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
